background: # avif for default, webp and jpeg for fallback
  avif: "/img/background/bg2.avif"
  webp: "/img/background/bg2.webp"
  jpeg: "/img/background/bg2.jpeg"
email: ChPu437@163.com
static: # 站长统计
  enable: true
  id: 1280890425
home:
  slogan: # 留空则使用 subtitle
post:
  comment:
    repo: ChPu437/blog-comment

