background: # avif for default, webp and jpeg for fallback
  # webp: "/img/background/bg3.webp"
  jpeg: "/img/background/bg.jpg"
email: ChPu437@163.com
home:
  slogan: # 留空则使用 subtitle
post:
  comment:
    repo: ChPu437/blog-comment
pages:
  links:
    enable: true
  about:
    enable: true
    avatar: /img/avatar/my_avatar.png # 头像路径
footer:
  timestamp: 2024
